import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./containers/header/Header";
import Animation from "./components/animation/Animation";
import animationDataLogo from "./components/animation/logo_wrangell.json";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css?family=Oswald"
          rel="stylesheet"
        ></link>
      </head>
      <body className={inter.className}>
        <div className="logo_animation">
          <Animation animationData={animationDataLogo} />
        </div>
        <main className="min-h-screen">
          <Header />
          {children}
        </main>
      </body>
    </html>
  );
}
